#ifndef MHTTP_REQ_HEADER_H
#define MHTTP_REQ_HEADER_H

/* Generated by statmatch.py */

#include <stdlib.h>

enum mhttp_req_header
{
  MHTTP_HEADER_AUTHENTICATE = 1,
  MHTTP_HEADER_CONNECTION,
  MHTTP_HEADER_CONTENT_LENGTH,
  MHTTP_HEADER_RANGE,
  MHTTP_HEADER_TRANSFER_ENCODING
};


static inline const char *mhttp_req_str_header(enum mhttp_req_header e)
{
  switch(e)
  {
    case MHTTP_HEADER_AUTHENTICATE:
      return "WWW-Authenticate:";
    case MHTTP_HEADER_CONNECTION:
      return "Connection:";
    case MHTTP_HEADER_CONTENT_LENGTH:
      return "Content-Length:";
    case MHTTP_HEADER_RANGE:
      return "Range:";
    case MHTTP_HEADER_TRANSFER_ENCODING:
      return "Transfer-Encoding:";
    default:
      return NULL;
  }
}


static inline enum mhttp_req_header mhttp_req_match_header(const char *str, const char **osp)
{
  enum mhttp_req_header res = 0;
  char c;
  c = *str++;
  switch(c)
  {
    case 'c':
    case 'C':
        c = *str++;
        switch(c)
        {
          case 'o':
          case 'O':
              c = *str++;
              switch(c)
              {
                case 'n':
                case 'N':
                    c = *str++;
                    switch(c)
                    {
                      case 'n':
                      case 'N':
                          c = *str++;
                          switch(c)
                          {
                            case 'e':
                            case 'E':
                                c = *str++;
                                switch(c)
                                {
                                  case 'c':
                                  case 'C':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 't':
                                        case 'T':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'i':
                                              case 'I':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'o':
                                                    case 'O':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'n':
                                                          case 'N':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case ':':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      default:
                                                                        res = MHTTP_HEADER_CONNECTION;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                      case 't':
                      case 'T':
                          c = *str++;
                          switch(c)
                          {
                            case 'e':
                            case 'E':
                                c = *str++;
                                switch(c)
                                {
                                  case 'n':
                                  case 'N':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 't':
                                        case 'T':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case '-':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'l':
                                                    case 'L':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'e':
                                                          case 'E':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'n':
                                                                case 'N':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'g':
                                                                      case 'G':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case 't':
                                                                            case 'T':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'h':
                                                                                  case 'H':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case ':':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              default:
                                                                                                res = MHTTP_HEADER_CONTENT_LENGTH;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 'r':
    case 'R':
        c = *str++;
        switch(c)
        {
          case 'a':
          case 'A':
              c = *str++;
              switch(c)
              {
                case 'n':
                case 'N':
                    c = *str++;
                    switch(c)
                    {
                      case 'g':
                      case 'G':
                          c = *str++;
                          switch(c)
                          {
                            case 'e':
                            case 'E':
                                c = *str++;
                                switch(c)
                                {
                                  case ':':
                                      c = *str++;
                                      switch(c)
                                      {
                                        default:
                                          res = MHTTP_HEADER_RANGE;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 't':
    case 'T':
        c = *str++;
        switch(c)
        {
          case 'r':
          case 'R':
              c = *str++;
              switch(c)
              {
                case 'a':
                case 'A':
                    c = *str++;
                    switch(c)
                    {
                      case 'n':
                      case 'N':
                          c = *str++;
                          switch(c)
                          {
                            case 's':
                            case 'S':
                                c = *str++;
                                switch(c)
                                {
                                  case 'f':
                                  case 'F':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'e':
                                        case 'E':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'r':
                                              case 'R':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case '-':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'e':
                                                          case 'E':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'n':
                                                                case 'N':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'c':
                                                                      case 'C':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case 'o':
                                                                            case 'O':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'd':
                                                                                  case 'D':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case 'i':
                                                                                        case 'I':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              case 'n':
                                                                                              case 'N':
                                                                                                  c = *str++;
                                                                                                  switch(c)
                                                                                                  {
                                                                                                    case 'g':
                                                                                                    case 'G':
                                                                                                        c = *str++;
                                                                                                        switch(c)
                                                                                                        {
                                                                                                          case ':':
                                                                                                              c = *str++;
                                                                                                              switch(c)
                                                                                                              {
                                                                                                                default:
                                                                                                                  res = MHTTP_HEADER_TRANSFER_ENCODING;
                                                                                                              }
                                                                                                              break;
                                                                                                        }
                                                                                                        break;
                                                                                                  }
                                                                                                  break;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 'w':
    case 'W':
        c = *str++;
        switch(c)
        {
          case 'w':
          case 'W':
              c = *str++;
              switch(c)
              {
                case 'w':
                case 'W':
                    c = *str++;
                    switch(c)
                    {
                      case '-':
                          c = *str++;
                          switch(c)
                          {
                            case 'a':
                            case 'A':
                                c = *str++;
                                switch(c)
                                {
                                  case 'u':
                                  case 'U':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 't':
                                        case 'T':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'h':
                                              case 'H':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'e':
                                                    case 'E':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'n':
                                                          case 'N':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 't':
                                                                case 'T':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'i':
                                                                      case 'I':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case 'c':
                                                                            case 'C':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'a':
                                                                                  case 'A':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case 't':
                                                                                        case 'T':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              case 'e':
                                                                                              case 'E':
                                                                                                  c = *str++;
                                                                                                  switch(c)
                                                                                                  {
                                                                                                    case ':':
                                                                                                        c = *str++;
                                                                                                        switch(c)
                                                                                                        {
                                                                                                          default:
                                                                                                            res = MHTTP_HEADER_AUTHENTICATE;
                                                                                                        }
                                                                                                        break;
                                                                                                  }
                                                                                                  break;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
  }

  if(osp)
  {
    *osp = str - 1;
  }

  return res;
}

#endif
