#ifndef MIDNIGHTTPD_CONFIG_OPT_H
#define MIDNIGHTTPD_CONFIG_OPT_H

/* Generated by statmatch.py */

#include <stdlib.h>

enum midnighttpd_config_opt
{
  MIDNIGHTTPD_CONFIG_DEFAULT_MIMETYPE = 1,
  MIDNIGHTTPD_CONFIG_DIRINDEX,
  MIDNIGHTTPD_CONFIG_LISTEN,
  MIDNIGHTTPD_CONFIG_LISTEN_UNIX,
  MIDNIGHTTPD_CONFIG_LOOP_SLOTS,
  MIDNIGHTTPD_CONFIG_MIMETYPE,
  MIDNIGHTTPD_CONFIG_ROOT,
  MIDNIGHTTPD_CONFIG_RXBUF,
  MIDNIGHTTPD_CONFIG_TXBUF
};


static inline const char *midnighttpd_str_config_opt(enum midnighttpd_config_opt e)
{
  switch(e)
  {
    case MIDNIGHTTPD_CONFIG_DEFAULT_MIMETYPE:
      return "default-mimetype:";
    case MIDNIGHTTPD_CONFIG_DIRINDEX:
      return "dirindex:";
    case MIDNIGHTTPD_CONFIG_LISTEN:
      return "listen:";
    case MIDNIGHTTPD_CONFIG_LISTEN_UNIX:
      return "listen-unix:";
    case MIDNIGHTTPD_CONFIG_LOOP_SLOTS:
      return "loop-slots:";
    case MIDNIGHTTPD_CONFIG_MIMETYPE:
      return "mimetype:";
    case MIDNIGHTTPD_CONFIG_ROOT:
      return "root:";
    case MIDNIGHTTPD_CONFIG_RXBUF:
      return "receive-buffer:";
    case MIDNIGHTTPD_CONFIG_TXBUF:
      return "transmission-buffer:";
    default:
      return NULL;
  }
}


static inline enum midnighttpd_config_opt midnighttpd_match_config_opt(const char *str, const char **osp)
{
  enum midnighttpd_config_opt res = 0;
  char c;
  c = *str++;
  switch(c)
  {
    case 'd':
        c = *str++;
        switch(c)
        {
          case 'e':
              c = *str++;
              switch(c)
              {
                case 'f':
                    c = *str++;
                    switch(c)
                    {
                      case 'a':
                          c = *str++;
                          switch(c)
                          {
                            case 'u':
                                c = *str++;
                                switch(c)
                                {
                                  case 'l':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 't':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case '-':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'm':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'i':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'm':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'e':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case 't':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'y':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case 'p':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              case 'e':
                                                                                                  c = *str++;
                                                                                                  switch(c)
                                                                                                  {
                                                                                                    case ':':
                                                                                                        c = *str++;
                                                                                                        switch(c)
                                                                                                        {
                                                                                                          default:
                                                                                                            res = MIDNIGHTTPD_CONFIG_DEFAULT_MIMETYPE;
                                                                                                        }
                                                                                                        break;
                                                                                                  }
                                                                                                  break;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
          case 'i':
              c = *str++;
              switch(c)
              {
                case 'r':
                    c = *str++;
                    switch(c)
                    {
                      case 'i':
                          c = *str++;
                          switch(c)
                          {
                            case 'n':
                                c = *str++;
                                switch(c)
                                {
                                  case 'd':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'e':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'x':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case ':':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          default:
                                                            res = MIDNIGHTTPD_CONFIG_DIRINDEX;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 'l':
        c = *str++;
        switch(c)
        {
          case 'i':
              c = *str++;
              switch(c)
              {
                case 's':
                    c = *str++;
                    switch(c)
                    {
                      case 't':
                          c = *str++;
                          switch(c)
                          {
                            case 'e':
                                c = *str++;
                                switch(c)
                                {
                                  case 'n':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case '-':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'u':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'n':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'i':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'x':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case ':':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            default:
                                                                              res = MIDNIGHTTPD_CONFIG_LISTEN_UNIX;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                        case ':':
                                            c = *str++;
                                            switch(c)
                                            {
                                              default:
                                                res = MIDNIGHTTPD_CONFIG_LISTEN;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
          case 'o':
              c = *str++;
              switch(c)
              {
                case 'o':
                    c = *str++;
                    switch(c)
                    {
                      case 'p':
                          c = *str++;
                          switch(c)
                          {
                            case '-':
                                c = *str++;
                                switch(c)
                                {
                                  case 's':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'l':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'o':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 't':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 's':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case ':':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      default:
                                                                        res = MIDNIGHTTPD_CONFIG_LOOP_SLOTS;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 'm':
        c = *str++;
        switch(c)
        {
          case 'i':
              c = *str++;
              switch(c)
              {
                case 'm':
                    c = *str++;
                    switch(c)
                    {
                      case 'e':
                          c = *str++;
                          switch(c)
                          {
                            case 't':
                                c = *str++;
                                switch(c)
                                {
                                  case 'y':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'p':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 'e':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case ':':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          default:
                                                            res = MIDNIGHTTPD_CONFIG_MIMETYPE;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 'r':
        c = *str++;
        switch(c)
        {
          case 'e':
              c = *str++;
              switch(c)
              {
                case 'c':
                    c = *str++;
                    switch(c)
                    {
                      case 'e':
                          c = *str++;
                          switch(c)
                          {
                            case 'i':
                                c = *str++;
                                switch(c)
                                {
                                  case 'v':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'e':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case '-':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 'b':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'u':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'f':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'f':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case 'e':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'r':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case ':':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              default:
                                                                                                res = MIDNIGHTTPD_CONFIG_RXBUF;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
          case 'o':
              c = *str++;
              switch(c)
              {
                case 'o':
                    c = *str++;
                    switch(c)
                    {
                      case 't':
                          c = *str++;
                          switch(c)
                          {
                            case ':':
                                c = *str++;
                                switch(c)
                                {
                                  default:
                                    res = MIDNIGHTTPD_CONFIG_ROOT;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
    case 't':
        c = *str++;
        switch(c)
        {
          case 'r':
              c = *str++;
              switch(c)
              {
                case 'a':
                    c = *str++;
                    switch(c)
                    {
                      case 'n':
                          c = *str++;
                          switch(c)
                          {
                            case 's':
                                c = *str++;
                                switch(c)
                                {
                                  case 'm':
                                      c = *str++;
                                      switch(c)
                                      {
                                        case 'i':
                                            c = *str++;
                                            switch(c)
                                            {
                                              case 's':
                                                  c = *str++;
                                                  switch(c)
                                                  {
                                                    case 's':
                                                        c = *str++;
                                                        switch(c)
                                                        {
                                                          case 'i':
                                                              c = *str++;
                                                              switch(c)
                                                              {
                                                                case 'o':
                                                                    c = *str++;
                                                                    switch(c)
                                                                    {
                                                                      case 'n':
                                                                          c = *str++;
                                                                          switch(c)
                                                                          {
                                                                            case '-':
                                                                                c = *str++;
                                                                                switch(c)
                                                                                {
                                                                                  case 'b':
                                                                                      c = *str++;
                                                                                      switch(c)
                                                                                      {
                                                                                        case 'u':
                                                                                            c = *str++;
                                                                                            switch(c)
                                                                                            {
                                                                                              case 'f':
                                                                                                  c = *str++;
                                                                                                  switch(c)
                                                                                                  {
                                                                                                    case 'f':
                                                                                                        c = *str++;
                                                                                                        switch(c)
                                                                                                        {
                                                                                                          case 'e':
                                                                                                              c = *str++;
                                                                                                              switch(c)
                                                                                                              {
                                                                                                                case 'r':
                                                                                                                    c = *str++;
                                                                                                                    switch(c)
                                                                                                                    {
                                                                                                                      case ':':
                                                                                                                          c = *str++;
                                                                                                                          switch(c)
                                                                                                                          {
                                                                                                                            default:
                                                                                                                              res = MIDNIGHTTPD_CONFIG_TXBUF;
                                                                                                                          }
                                                                                                                          break;
                                                                                                                    }
                                                                                                                    break;
                                                                                                              }
                                                                                                              break;
                                                                                                        }
                                                                                                        break;
                                                                                                  }
                                                                                                  break;
                                                                                            }
                                                                                            break;
                                                                                      }
                                                                                      break;
                                                                                }
                                                                                break;
                                                                          }
                                                                          break;
                                                                    }
                                                                    break;
                                                              }
                                                              break;
                                                        }
                                                        break;
                                                  }
                                                  break;
                                            }
                                            break;
                                      }
                                      break;
                                }
                                break;
                          }
                          break;
                    }
                    break;
              }
              break;
        }
        break;
  }

  if(osp)
  {
    *osp = str - 1;
  }

  return res;
}

#endif
